// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0Y0s8OuX2bBRpqiBq_BRYCBK4cywLgN0',
    appId: '1:348108271940:web:5e02841fa1c9df18b36711',
    messagingSenderId: '348108271940',
    projectId: 'guardianeyemain',
    authDomain: 'guardianeyemain.firebaseapp.com',
    storageBucket: 'guardianeyemain.appspot.com',
    measurementId: 'G-YS9SLD98N5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8sgS1GFmWTGIBDqqI0OYRqpTjBXucaEg',
    appId: '1:348108271940:android:9b3d1f68c7963deeb36711',
    messagingSenderId: '348108271940',
    projectId: 'guardianeyemain',
    storageBucket: 'guardianeyemain.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjv4UfiuVf3DjgriugIvaHfQeNkicQmcg',
    appId: '1:348108271940:ios:b5edc38b142f4a4cb36711',
    messagingSenderId: '348108271940',
    projectId: 'guardianeyemain',
    storageBucket: 'guardianeyemain.appspot.com',
    iosBundleId: 'com.example.guardianeye',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjv4UfiuVf3DjgriugIvaHfQeNkicQmcg',
    appId: '1:348108271940:ios:b5edc38b142f4a4cb36711',
    messagingSenderId: '348108271940',
    projectId: 'guardianeyemain',
    storageBucket: 'guardianeyemain.appspot.com',
    iosBundleId: 'com.example.guardianeye',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0Y0s8OuX2bBRpqiBq_BRYCBK4cywLgN0',
    appId: '1:348108271940:web:8909601656d7343bb36711',
    messagingSenderId: '348108271940',
    projectId: 'guardianeyemain',
    authDomain: 'guardianeyemain.firebaseapp.com',
    storageBucket: 'guardianeyemain.appspot.com',
    measurementId: 'G-YEFP0SW8X9',
  );
}
